//TEMPLE DE LOEIL AVEUGLE

// Generation de la pretresse emprisonnée ///////////////
IF                                                     //
Global("CKPretressespawn","AR0202",0)  
Global("CKquete1","Global",4)                          //
THEN                                                   //
RESPONSE #100                                          //
SetGlobal("CKPretressespawn","AR0202",1)               //
CreateCreature("CKFelic2",[2220.1576],13)              //
END                                                    //
/////////////////////////////////////////////////////////


// Generation des gardes kobolds ////////////////////////
IF                                                     //
Global("CKKoboldspawn","AR0202",0)
Global("CKquete1","Global",7)                          //
THEN                                                   //
RESPONSE #100                                          //
SetGlobal("CKKoboldspawn","AR0202",1)               //
CreateCreature("CKKobold",[2411.2164],13)              //
CreateCreature("CKKobold",[2500.2089],13)              //
CreateCreature("CKKobold",[2754.1874],13)              //
CreateCreature("CKKobold",[2736.1917],13)              //
CreateCreature("CKKobold",[3049.2010],13)              //
CreateCreature("CKKobold",[2408.1961],13)              //
CreateCreature("CKKobold",[2261.2071],13)              //
CreateCreature("CKKobol2",[1450.2135],13)              //
CreateCreature("CKKobold",[1504.2028],13)              //
END                                                    //
/////////////////////////////////////////////////////////

// Generation de la Paladine et des acolytes ////////////
IF                                                     //
Global("CKpaladinespawn","AR0202",0)                   //
Global("CKquete1","Global",8)                          //
THEN                                                   //
RESPONSE #100                                          //
SetGlobal("CKpaladinespawn","AR0202",1)                //
CreateCreature("CKFidelF",[2414.2164],13)              //
CreateCreature("CKFidelF",[2414.2164],13)              //
CreateCreature("CKFidelF",[2414.2164],13)              //
CreateCreature("CKFidelH",[2414.2164],13)              //
CreateCreature("CKFidelH",[2414.2164],13)              //
CreateCreature("CKFidelH",[2414.2164],13)              //
END                                                    //
/////////////////////////////////////////////////////////

