//MAP DE LA PRISON DU QUARTIER DU GOUVERNEMENT

// Generation de la pretresse emprisonnée /////////////
IF
	Global("CKPretressespawn","MYAREA",0)
THEN
	RESPONSE #100
		SetGlobal("CKPretressespawn","MYAREA",1)
		Wait(2)
		CreateCreature("CKFelici",[499.765],13)
		Continue()
END
///////////////////////////////////////////////////////

// Generation du garde a clef  ////////////////////////
IF
	Global("CKGardespawn","MYAREA",0)
THEN
	RESPONSE #100
		SetGlobal("CKGardespawn","MYAREA",1)
		Wait(2)
		CreateCreature("CKBAMN",[630.350],13)
		Continue()
END
///////////////////////////////////////////////////////
